#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

# Visual options
bspc config border_width                        1
bspc config window_gap                          2
bspc config top_padding                         13
bspc config normal_frame_opacity                0.0
bspc config focused_frame_opacity               0.1
bspc config fence_grip                          100
bspc config split_ratio                         0.52

bspc config borderless_monocle                  false
bspc config gapless_monocle                     true
bspc config adaptative_raise                    true
bspc config focus_follows_pointer               true
bspc config click_to_focus                      true
bspc config auto_alternate                      true
bspc config auto_cancel                         true

bspc config normal_border_color                 "#3F0000"
bspc config active_border_color                 "#004455"
bspc config focused_border_color                "#544F4B"
bspc config presel_border_color                 "#9A875F"
bspc config urgent_border_color                 "#9F7155"
bspc config focused_locked_border_color         "#9a875f"

# Autostart
yabar &
