#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

# Visual options
bspc config border_width						2
bspc config window_gap							23
bspc config split_ratio                         0.52

bspc config borderless_monocle                  false
bspc config gapless_monocle                     false
bspc config focus_follows_pointer               true
bspc config auto_alternate                      true
bspc config auto_cancel                         true

bspc config normal_border_color                 "#6D3322"
bspc config active_border_color                 "#6D3322"
bspc config focused_border_color                "#F0E4D8"
bspc config presel_border_color                 "#9a875f"
bspc config urgent_border_color                 "#9f7155"
bspc config focused_locked_border_color         "#9a875f"
bspc config normal_frame_opacity                1.0
bspc config focused_frame_opacity               1.0
bspc config active_frame_opacity                1.0

yabar &
