# Start dbus-launch
dbus-launch &

# Set wallpaper
feh --randomize --bg-fill ~/Pictures/Wallpapers

# Composite manager
xcompmgr &

# Start PulseAudio
start-pulseaudio-x11 &

# Start Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start Unclutter
unclutter &

# Start MPD
mpd &

# Start Caffeine
caffeine &

# Set fonts
xset +fp /usr/share/fonts/local
xset +fp ~/.fonts
xset fp rehash

# Turn NumLock on
numlockx &

# Set xautolock locker
xautolock -locker i3lock-fancy &

# Set keyboard layout
setxkbmap -layout tr

# Cursor
xsetroot -cursor_name left_ptr &

# Execute wm with keybindings
sxhkd &
exec bspwm
