#!/bin/sh

pkill -x rofi

rofi -show drun \
	 -font "Droid Sans 8" \
	 -lines 12 \
	 -location 1 \
	 -yoffset 13 \
	 -xoffset 0 \
	 -width 200 \
	 -hide-scrollbar true \
	 -modi drun,window \
	 -sidebar-mode true \
	 -kb-mode-next Tab \
	 -display-drun "Run" \
	 -display-window "Switch to" \
	 -color-window "#070708, #070708, #070708" \
	 -color-normal "#070708, #BFBFBF, #070708, #394249, #BFBFBF" \
	 -color-active "#070708, #BFBFBF, #070708, #394249, #BFBFBF"

>/dev/null
