#!/bin/bash

timestamp="$(date +%Y%m%d%H%M%S)"
targetbase="$HOME/Pictures/Screenshots/"
mkdir -p $targetbase
[ -d $targetbase ] || exit 1
scrot $targetbase/$timestamp.png

sudo -u ertseyhan notify-send "Screenshot" "Ekran görüntüsü $timestamp.png kaydedildi!"
