#!/bin/bash

show_help() {
	echo -e "Usage: $0 [command]\n"
	echo "Available options:"
	echo -e "  [no command] \t\t toggles the state of the touchpad."
	echo -e "  enable \t\t enables the touchpad."
	echo -e "  disable\t\t disables the touchpad."
}

touchpadID=$(xinput | grep -i touchpad | sed 's/.*id=\(.*\)\t.*/\1/')
current=$(xinput list-props $touchpadID | grep "Device Enabled" | sed 's/.*):\t\(.*\).*/\1/')

if [[ $1 == "-h" || $1 == "--help" ]]
	then
		show_help
		exit 0
	fi

if [[ $1 == "enable" || $current == 0 ]]
	then
		xinput set-prop $touchpadID "Device Enabled" 1
	fi

if [[ $1 == "disable" || $current == 1 ]]
	then
		xinput set-prop $touchpadID "Device Enabled" 0
	fi
