#!/bin/bash

vol=$(pamixer --get-volume)

if [[ ${vol} -ge 66 ]]; then # distinguish the volume symbols
    echo -ne "\uf028"
elif [[ ${vol} -lt 66 ]] && [[ ${vol} -ge 33 ]]; then
    echo -ne "\uf027"
else
    echo -ne "\uf026"
fi

echo "  ${vol}%"
